### ISSUE TITLE
Connecting Cerberus-UX with the Backend

### ISSUE THREAD

**Issue by JBort** [ovh/cerberus-core#13]
there where some smaller dependency issues and the app.less wasnt compiled right to app.css

testing with the express server of cerberus-ux trying to use the backend, im getting the following error:

$ npm start

> abuse@0.2.16 start /home/roland/cerberus-ux
> node server

Express server listening on 9000, in development mode
[REMOTE] POST /api/auth
Error: Invalid URI "/api/auth"
    at Request.init (/home/roland/cerberus-ux/node_modules/request/request.js:273:31)
    at new Request (/home/roland/cerberus-ux/node_modules/request/request.js:127:8)
    at request (/home/roland/cerberus-ux/node_modules/request/index.js:53:10)
    at /home/roland/cerberus-ux/server/proxy/remote/index.js:12:13
    at Layer.handle [as handle_request] (/home/roland/cerberus-ux/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/roland/cerberus-ux/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/roland/cerberus-ux/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/roland/cerberus-ux/node_modules/express/lib/router/layer.js:95:5)
    at /home/roland/cerberus-ux/node_modules/express/lib/router/index.js:281:22
    at param (/home/roland/cerberus-ux/node_modules/express/lib/router/index.js:354:14)
POST /api/auth 500 12.408 ms - -
[REMOTE] POST /api/logout
Error: Invalid URI "/api/logout"
    at Request.init (/home/roland/cerberus-ux/node_modules/request/request.js:273:31)
    at new Request (/home/roland/cerberus-ux/node_modules/request/request.js:127:8)
    at request (/home/roland/cerberus-ux/node_modules/request/index.js:53:10)
    at /home/roland/cerberus-ux/server/proxy/remote/index.js:12:13
    at Layer.handle [as handle_request] (/home/roland/cerberus-ux/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/roland/cerberus-ux/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/roland/cerberus-ux/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/roland/cerberus-ux/node_modules/express/lib/router/layer.js:95:5)
    at /home/roland/cerberus-ux/node_modules/express/lib/router/index.js:281:22
    at param (/home/roland/cerberus-ux/node_modules/express/lib/router/index.js:354:14)
POST /api/logout 500 1.537 ms - -

using an apache2 and putting dist/client/ into var/www wasnt helping 

how to connect it?

**Comment by JBort** [comment]
i saw some proxy rerouting and other things going on, im not sure if this error may come from something from /cerberus-ux/server/proxy/remote/index.js:12:13

or maybe cerberus-core/api/views/misc.py:38+59

what is the strive for start sequence
